### ISSUE TITLE
Placeholder issue

### ISSUE THREAD

**Issue by Davvie** [nicklockwood/FXForms#138]
When you set the fields in code placeholders still show up
![865t0bedglo](https://cloud.githubusercontent.com/assets/816045/3487039/9734da06-045f-11e4-94d5-6361f33a35ed.jpg)

**Comment by resisi** [comment]
Hey @nicklockwood 
i still have this issue :/

May you can help me?

![image](https://cloud.githubusercontent.com/assets/14897039/10179066/d880669e-6703-11e5-889b-fb079e505a7a.png)
