### ISSUE TITLE
Auto dismiss option subcontroller on select

### ISSUE THREAD

**Issue by ReDetection** [nicklockwood/FXForms#163]
Why I should force user to tap one more time? 

It seems, there are only two ways now to implement it without FXForms code modification: subclassing FXFormViewController and querying nextResponders in the action block.

**Comment by frakman1** [comment]
My easy solution was to associate an action to the form field and popping the view off the navigation stack
```objective-c
@{FXFormFieldKey: @"attorney", FXFormFieldTitle:@"Pick Attorney",
     FXFormFieldOptions: ([self.sortableArray count] ? self.sortableArray : @[]),
     FXFormFieldAction: @"pickedAttorney:"
     },
```
then
```objective-c
- (void) pickedAttorney:(UITableViewCell<FXFormFieldCell> *)cell
{
    [self.navigationController popViewControllerAnimated:YES];
}
```
Hope that helps.

**Comment by ReDetection** [comment]
ok, good enough.
