### ISSUE TITLE
Subforms do not display inline properly in Swift

### ISSUE THREAD

**Issue by justinmakaila** [nicklockwood/FXForms#199]
Forms do not seem to display properly inline in Swift.

Screen shot:
![](https://cloud.githubusercontent.com/assets/1638996/4534827/2720729a-4daa-11e4-964a-c155268e7a21.png)
My view controller:

```
class ViewController: UIViewController, FXFormControllerDelegate {
    @IBOutlet var tableView: UITableView!
    var formController: FXFormController = FXFormController()
    var settingsForm: SettingsForm!

    override func viewDidLoad() {
        super.viewDidLoad()

        var currentUser = User()
        self.settingsForm = SettingsForm(user: currentUser)

        self.formController.tableView = tableView
        self.formController.delegate = self
        self.formController.form = settingsForm
    }

    override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)

        tableView.reloadData()
    }
}
```

Settings Form:

```
typealias FXFormFieldDictionary = [NSObject: AnyObject]

class SettingsForm: NSObject, FXForm {
    var userProfile: UserProfileForm
    var legal: LegalForm = LegalForm()

    init(user: User) {
        self.userProfile = UserProfileForm(user: user)
    }

    func userProfileField() -> FXFormFieldDictionary {
        return [
            FXFormFieldInline: true
        ]
    }

    func legalField() -> FXFormFieldDictionary {
        return [
            FXFormFieldInline: true
        ]
    }
}
```

User Profile Form:

```
class UserProfileForm: NSObject, FXForm {
    var fullName: String
    var userDescription: String
    var email: String

    init(user: User) {
        self.fullName = user.fullName
        self.userDescription = user.userDescription
        self.email = user.email
    }

    func fullNameField() -> FXFormFieldDictionary {
        return [
            FXFormFieldHeader: "User Profile",
            FXFormFieldTitle: "Full Name"
        ]
    }

    func userDescriptionField() -> FXFormFieldDictionary {
        return [
            FXFormFieldTitle: "Description",
            FXFormFieldType: FXFormFieldTypeLongText
        ]
    }

    func emailField() -> FXFormFieldDictionary {
        return [
            FXFormFieldTitle: "Email",
            FXFormFieldType: FXFormFieldTypeEmail
        ]
    }
}
```

Legal Form:

```
class LegalForm: NSObject, FXForm {
    var termsOfService = WebViewController(url: NSURL(string: "http://present.tv/terms.txt"))
    var privacyPolicy = WebViewController(url: NSURL(string: "http://present.tv/privacy.txt"))

    func fields() -> [AnyObject]! {
        return [
            "termsOfService",
            "privacyPolicy"
        ]
    }
}
```

**Comment by kumargaurav89** [comment]
i am using iOS. but still getting the same error. when i am trying to call the another view.

2015-11-19 01:06:27.818 *********[5791:274702] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Attempted to push a sub-viewController from a form that is not embedded inside a UINavigationController. That won't work!'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010651af45 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000108466deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010651adaa +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x0000000107e8b5ee -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   Simply Hearing Mobile               0x00000001062b33c3 -[FXFormDefaultCell didSelectWithTableView:controller:] + 6883
	5   Simply Hearing Mobile               0x00000001062ad699 -[FXFormController tableView:didSelectRowAtIndexPath:] + 217
	6   UIKit                               0x0000000106a07a21 -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:] + 1968
	7   UIKit                               0x0000000106a07c76 -[UITableView _userSelectRowAtPendingSelectionIndexPath:] + 388
	8   UIKit                               0x00000001068d31ba _runAfterCACommitDeferredBlocks + 317
	9   UIKit                               0x00000001068e6396 _cleanUpAfterCAFlushAndRunDeferredBlocks + 95
	10  UIKit                               0x00000001068f21c2 _afterCACommitHandler + 90
	11  CoreFoundation                      0x0000000106446947 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	12  CoreFoundation                      0x00000001064468b7 __CFRunLoopDoObservers + 391
	13  CoreFoundation                      0x000000010643c50b __CFRunLoopRun + 1147
	14  CoreFoundation                      0x000000010643be08 CFRunLoopRunSpecific + 488
	15  GraphicsServices                    0x0000000109e0bad2 GSEventRunModal + 161
	16  UIKit                               0x00000001068c730d UIApplicationMain + 171
	17  Simply Hearing Mobile               0x0000000106278bdf main + 111
	18  libdyld.dylib                       0x0000000108d8a92d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by nicklockwood** [comment]
@kumargaurav89 Is your formViewController inside a UINavigationController? It needs to be if you want to use non-inline subforms.

**Comment by kumargaurav89** [comment]
hi nicklockwood.

i am using tab view controller, there is no navigation controller. so is there any way to solve this issue?
