### ISSUE TITLE
How do you make the tableView of the form a subview of your main view?

### ISSUE THREAD

**Issue by sebinsua** [nicklockwood/FXForms#215]
"Like UITableViewController, FXFormViewController will normally assign the tableView as the main view of the controller. Unlike UITableViewController, it doesn't have to be - you can make your tableView a subview of your main view if you prefer."

How is this done? I wish to use a custom navigation bar on this page, that is distinct from the UINavigationController's UINavigationBar and currently the parent view that I setup with Storyboards is being overwritten by the form destroying my navigation bar.

**Comment by Jamongkad** [comment]
I know this is closed. But can you please provide an example on how to do this programmatically?

**Comment by rounak** [comment]
Create your own tableView, add it as a subview, and assign it to `formController.tableView`

**Comment by Jamongkad** [comment]
Thanks Rounak I'll try that.

**Comment by Jamongkad** [comment]
Hello I tried you suggestion and I'm running into some difficulties. Here is the code from my UIViewController viewDidLoad method...

   UITableView *table = [[UITableView alloc] init];
    [table setDelegate:self];
    [table setDataSource:self];
    [table registerClass:[UITableViewCell class] forCellReuseIdentifier:@"MyCell"];
    [self.view addSubview:table];
    
   
    FXFormViewController *controller = [[FXFormViewController alloc] init];
    controller.tableView = table;
    controller.formController.form = [[LocalBankForm alloc] init];

This is my code. When I compile it I get this error 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[3]'

This is the code to my LocalBankForm model...

    @implementation LocalBankForm

    @synthesize bank, accountType, accountName, accountNumber;

    -(id)init{
    if(self = [super init]) {
        self.banks = @[
            @"ABC",
            @"AUB",
            @"BOA",
            @"BDO",
            @"BPI",
            @"CBC",
            @"CIT",
            @"EWB",
            @"EWR",
            @"HSB",
            @"LBP",
            @"MAY",
            @"MET",
            @"PBC",
            @"PNB",
            @"RCBC",
            @"SEC",
            @"SCB",
            @"UBP",
            @"UCP",
        ];
    }
    return self;
    }

    -(NSArray *)fields {
    return @[
              @{FXFormFieldKey: @"bank",
                FXFormFieldOptions: self.banks,
                FXFormFieldValueTransformer: [[BankTransformer alloc] init],
                FXFormFieldDefaultValue: self.bank,
              },
              @{FXFormFieldKey: @"accountType",
                FXFormFieldOptions: @[@"Current", @"Savings"],
                FXFormFieldDefaultValue: @"Current",
              },
              @{FXFormFieldKey: @"accountName", FXFormFieldTitle: @"Account Name"},
              @{FXFormFieldKey: @"accountNumber", FXFormFieldTitle: @"Account Number"},
            ];
    }
    @end

**Comment by rounak** [comment]
Don't think you need to set the dataSource

**Comment by Jamongkad** [comment]
UITableView *table = [[UITableView alloc] init];
    //[table setDelegate:self];
    //[table setDataSource:self];
    //[table registerClass:[UITableViewCell class] forCellReuseIdentifier:@"MyCell"];
    [self.view addSubview:table];

    FXFormViewController *controller = [[FXFormViewController alloc] init];
    controller.tableView = table;
    controller.formController.form = [[LocalBankForm alloc] init];

I commented out the following code and I still get the same error....
