### ISSUE TITLE
Two fields in a Cell

### ISSUE THREAD

**Issue by westongpt** [nicklockwood/FXForms#248]
I am trying to combine a two fields for state and zip code into a single cell. The framework really doesn't seem to like it, we want state to be a picker and zip to be a text field. Do you have any pointers on implementing this? I am having a hell of a time.

**Comment by mbesnili** [comment]
@Kronusdark would you mind sharing your code showing that how you did it, i'm having hard time implementing something similar ?

**Comment by lazyneighbour** [comment]
@Kronusdark I'm struggling with exact same issue here, I would be thankfull if you could help me
