### ISSUE TITLE
Pass objects to form instance

### ISSUE THREAD

**Issue by kstole** [nicklockwood/FXForms#277]
I just started using FXForms and I'm very impressed with its automatic behavior.

I'm having difficulty finding a way to send an object represented by a table row to the form and I know there must be a way to do this.

Currently, I use prepareForSegue in the root view controller to send the selected object to my custom FXFormViewController, which works successfully. However, it's in the ViewController only and I need to use it in the form (the model). Sending it as an init in awakeFromNib doesn't work because awakeFromNib runs before prepareForSegue and using viewDidLoad instead of awakeFromNib causes the form to not show.

What is the best way to send something to an FXForm?

**Comment by jakelisby** [comment]
+1 trying to do the same thing.

**Comment by nicklockwood** [comment]
I'm not sure I fully understand what you mean by "Send the selected object"? What kind of object is it? Is it one of the values represented by a field in your form object?

If so, you can access the form from within a FXFormViewController subclass like this:

    MyForm *form = (MyForm *)self.formController.form;
    form.someProperty = valueFromSegue;

Then you can set one of its properties, and then reload the table using 

    [self.formController.tableView reloadData];

To see the updated value appear. Or, if the object from the segue actually is an entire form in its own right, you can just assign it to self.formController.form.

If that's not what you mean, please explain further.

**Comment by jakelisby** [comment]
Mine is a dictionary of keys and I'm trying to pass it to the form and set the fields default values to the values of keys. Essentially I'm selecting a row from a table that represents a person's profile, then loading the form for editing, and want to pre-populate the fields.

**Comment by nicklockwood** [comment]
Try calling setValuesForKeysWithDictionary: On your form object. If the keys and types match up with the properties, it should work (otherwise it will crash)

**Comment by jakelisby** [comment]
Awesome, thanks a ton for your help!
