### ISSUE TITLE
Issue in setting NSArray in FXForm object with options and ValueTransformer

### ISSUE THREAD

**Issue by billykan** [nicklockwood/FXForms#289]
I am wondering if I have hit a bug or I've done something wrong. Here is my scenario:

- I have an <FXForm> object with an NSArray property, let's call it X.
- In the XField method, I've set an array of strings as FXFormFieldOptions and also a ValueTransformer object as FXFormFieldValueTransformer for the field. The ValueTransformer will map each string in the options array to a user display string.
- When I run the app and the tap on the X field, the options are presented in a new ViewController as expected and they are displayed as the user display strings.
- After I pick a couple of options (as X is an array and so multiple selection is allowed) and tap back. Field X shows all the values I've selected. However, instead of showing the display strings, it show the strings in the option array instead.

The issue only appears if the field is an array. If it's just a string (and so only single selection is allowed), the selected option is displayed correctly in the display string.

**Comment by nicklockwood** [comment]
Sounds like a bug. I'll take a look.

**Comment by nicklockwood** [comment]
Fixed in 1.2.11

**Comment by billykan** [comment]
The fix works perfect. Many thanks!
