### ISSUE TITLE
NSOrderedArray of emails, with unverified and verified, and ability to "resend" verification, and not editable once "set"

### ISSUE THREAD

**Issue by jonathantrevor** [nicklockwood/FXForms#292]
FXForms so far has been great - got something up and running very quickly for changing a users settings in their profile. Im struggling with displaying a list of emails the user has, with some very specific behavior:

* entries in the list cannot be edited but can be deleted
* new entries can be added AND edited. Once valid they are "done"
* entries with a specific state (unverified) should display differently and present an additional button "Resend"

Im really not sure what combination of FXForm elements to use for this.

For the array I've created this entry in the form:
```
-(NSDictionary*)otherEmailsField
{
    return @{
             FXFormFieldInline: @YES,
             FXFormFieldTemplate: @{
                     FXFormFieldType: FXFormFieldTypeDefault,
                     FXFormFieldCell: [SISFormEmailCell class],
                     FXFormFieldTitle: @"Add another email"
                     }
             };
}
```
The SISFormEmailCell looks like this:

```
@interface SISFormEmailCell : FXFormDefaultFieldCell
@end

@interface SISFormEmailCell ()

@property (nonatomic, strong) UIButton *resendButton;
@property (nonatomic, strong) UITextField* textField;
@property (nonatomic, strong) SISOtherEmail* oe;
@end

@implementation SISFormEmailCell

-(id)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier
{
    self = [super initWithStyle:style reuseIdentifier:reuseIdentifier];
    self.textField = [[UITextField alloc] init];
    self.resendButton = [UIButton buttonWithType:UIButtonTypeContactAdd];
    [self.contentView addSubview:self.resendButton];
    [self.contentView addSubview:self.textField];
    return self;
}

- (void)setUp
{
    [super setUp];
}

- (void)update
{
    self.oe = self.field.value;
    if (!self.oe) {
        // new field
        self.textField.enabled = TRUE;
        self.resendButton.hidden = TRUE;
    } else {
        self.textField.text = self.oe.email;
        self.textField.enabled = FALSE;
        if (self.oe.verified) {
            self.resendButton.hidden = TRUE;
        } else {
            self.resendButton.hidden = FALSE;
        }
    }
}

- (void)layoutSubviews
{
    [super layoutSubviews];
    self.textField.frame = self.contentView.bounds;
    self.textField.placeholder = @"Enter email";
    self.resendButton.frame = CGRectMake(self.contentView.sizeWidth - self.resendButton.sizeWidth, 0, self.resendButton.sizeWidth, self.resendButton.sizeHeight);
}

@end
```

So this is close but I'd like to somehow stop the user from entering an "invalid" email into the box when its first "added" and is in editable state (and delete the entry if they stop editing it). Whats the best way to do that? Or is this approach simply not the best way to do this using FXForms?

Tips or hints appreciated.

**Comment by nicklockwood** [comment]
The template title was supposed to be used only for the “Add Item” button, but was appearing inside each field. I’ve fixed that in 1.2.12.

Once you upgrade to 1.2.12, if you just want a blank text field, you shouldn’t need to do anything further to customize your cell - you can just use a standard FXFormTextFieldCell.

The only thing that isn't supported is making the email fields non-editable after they've been created. You might be able to rig that up using a custom cell, but I'm not exactly sure what the best way to do that would be - maybe replace the strings in your array with some kind of object that has an editable state?.

Note that if a user edits any existing entries, it will call the setter on your form for the whole list, so you can apply any necessary re-validation logic. It may not be necessary for you to make them non-editable, unless it's particularly desirable for UX reasons.

If you want to apply custom styling then subclassing FXFormTextFieldCell as you were doing is the correct approach. The cell has a “field” property that contains all the available state information.

Nick
