### ISSUE TITLE
FXFormFieldAction not firing on textField value change

### ISSUE THREAD

**Issue by imaks** [nicklockwood/FXForms#306]
Quote from the docs about `FXFormFieldAction`: 
> for fields such as switches or textfields, it wll fire when the value is changed.

However, for `FXFormTextFieldCell` it doesn't fire in [textDidChange](https://github.com/nicklockwood/FXForms/blob/master/FXForms/FXForms.m#L2950-L2953), only in [textFieldDidEndEditing:](https://github.com/nicklockwood/FXForms/blob/master/FXForms/FXForms.m#L2972)
Is this an expected behaviour?

**Comment by nicklockwood** [comment]
Yes, but mostly because that property is rather poorly defined, and has suffered some scope creep. It really needs to be broken up into separate events.

To detect every text change, I suggest you add a KVC observer to your form field, or override the setter and have it call an action directly.

**Comment by imaks** [comment]
OK, I've come up with KVO on text change. Thanks, Nick!
