### ISSUE TITLE
Implementing custom cell not working as expected

### ISSUE THREAD

**Issue by Slijkhuis** [nicklockwood/FXForms#315]
I want to 'override' the styling of all `FXFormTextFieldCell`s. I read through the README and my understanding of how to do this is that I should create my own class (e.g., `MyFormTextFieldCell`) that extends `FXFormTextFieldCell`. Then I should register this as the text-field class by calling `-registerCellClass:forFieldClass:`. So, in my view controller (which implements `FXFormControllerDelegate`) I have this:

    - (instancetype)init {
        
        if(self = [super init]) {
            NSLog(@"I can see this log. And no errors are thrown whatsoever.");
            
            // I tried this
            //[self.formController registerCellClass:[MyFormTextFieldCell class] forFieldClass:[NSString class]];
            
            // And this:
            //[self.formController registerCellClass:[MyFormTextFieldCell class] forFieldClass:[FXFormTextFieldCell class]];
            
            // And this:
            [self.formController registerCellClass:[MyFormTextFieldCell class] forFieldType:@"text"];
            
            // None of them work...
        }
        return self;
        
    }

In `MyFormTextFieldCell`:

    - (void)setUp {
        [super setUp];
        self.backgroundColor = [UIColor clearColor];
    }

When I use `FXFormFieldClass: @"MyFormTextFieldCell"` in the `- (NSArray*) fields`-method of my form, it's fine. But I don't want to include this for every field.

Am I doing something wrong? Any suggestions on how to style one type of field for the entire form?

**Comment by nicklockwood** [comment]
It should be:

    [self.formController registerCellClass:[MyFormTextFieldCell class] forFieldType: FXFormFieldTypeText];

Which tells FXForms to use your MyFormTextFieldCell for any field of type FXFormFieldTypeText. If it's not working, have you verified that self.formController is not nil inside your init method?

**Comment by Slijkhuis** [comment]
I hadn't.. The formController was indeed nil. So, I moved it to `viewDidLoad` and it worked!

E-mail, phone and password fields are however still in the default style, but those have different field types I guess. Is there a way to cover each of those at once? So, if I'd do this:

     [self.formController registerCellClass:[MyFormTextFieldCell class] forFieldType:FXFormFieldTypeText];
     [self.formController registerCellClass:[MyFormTextFieldCell class] forFieldType:FXFormFieldTypePhone];
     [self.formController registerCellClass:[MyFormTextFieldCell class] forFieldType:FXFormFieldTypePassword];
     [self.formController registerCellClass:[MyFormTextFieldCell class] forFieldType:FXFormFieldTypeEmail];

Can I retrieve the field type in the `setUp` method of `MyFormTextFieldCell`? Because then I can manually recreate the keyboard, autocorrect and secureTextEntry behaviour for each of those types, or are different in more ways?

**Comment by nicklockwood** [comment]
If you subclass FXFormTextFieldCell then it should handle the different keyboards, etc. automatically.

You can't get the field type in setUp, but in update you can check self.field.type.

**Comment by Slijkhuis** [comment]
Thanks! Amazing library and amazing support :+1:
