### ISSUE TITLE
How to set default value for enum list?

### ISSUE THREAD

**Issue by yihshin** [nicklockwood/FXForms#339]
Not sure if I can ask question here. I'm sorry if I'm not supposed to.

I've got an ENUM <nationality> filled with bunch of options. How can I set a default one instead of it default to the first one everytime?

**Comment by nicklockwood** [comment]
You can set a default value in your form configuration for that field, e.g.

    - (NSDictionary *)myPropertyField
    {
        return @{FXFormFieldDefaultValue: @3}; // number equal to enum value you want to be default
    }

Alternatively, in the init for your form object, you can just set the default, like this:

    - (id)init
    {
        if ((self = [super init])) {
            _myProperty = SOME_ENUM_VALUE;
        }
    }

**Comment by yihshin** [comment]
I do something like this
    @{FXFormFieldKey:@"gender", FXFormFieldTitle: @"Gender", FXFormFieldOptions: @[@"Male",@"Female"],FXFormFieldDefaultValue: @1}


with 

    typedef NS_ENUM(NSInteger, Gender)
    {
        GenderMale = 0,
        GenderFemale,
    };

 in the header file.

supposedly it will set default value to female, right? But it doesn't seems to work so. Am i doing it wrongly?

**Comment by lzwjava** [comment]
@yihshin 
try use 
```
- (id)init
{
    if ((self = [super init])) {
        _myProperty = SOME_ENUM_VALUE;
    }
}
```

works great ！

**Comment by wdcurry** [comment]
@tzwjava: you are not returning the reference to self in your example.
`- (id)init
{
    if ((self = [super init])) {
        _myProperty = SOME_ENUM_VALUE;
    }
    **return self;**
}`

**Comment by nicklockwood** [comment]
@wdcurry thanks, I've updated my original answer.

(ps, to indent code correctly on github, just add four spaces at the start of each line.)
