### ISSUE TITLE
How to pass property via Form ?

### ISSUE THREAD

**Issue by dehlen** [nicklockwood/FXForms#342]
Hello,

I got a FXForm which implements some UIViewController propertys in order to push to these UIViewControllers when a cell is clicked.

```
@property (nonatomic,strong) DESettingsChangeViewController *myProperty;
```

This all works fine. Unfortunately I would like to pass some parameter while pushing the UIViewController. How can I do it ? The whole navigation-logic is made by the library and I do not see any possibility to pass some parameters.

For example my ```DESettingsChangeViewController``` has a property ```NSString *type;``` which I would like to fill from the FXForm when the push is made.

I encountered that when I click on the cell the UIViewControllers title gets set. This would be enough information for me, because I use 1 UIViewController for 3 cells which all do similiar things and therefore I don't want to implement 3 different UIViewControllers. Thats why I need to know which cell is clicked. I could go with the viewcontrollers title but this looks to me like a messy hack and there should be the possibility to pass some custom defined property too.

**Comment by JJJJJJJerk** [comment]
i do not know how to get the property of a cell in the TVC either!

**Comment by nicklockwood** [comment]
If your View controller has a property called field of type FXFormField, it will be set automatically to the field of the cell that was clicked. You can include any data you want to pass as that field's value.

**Comment by dehlen** [comment]
Great thanks for the support.
