### ISSUE TITLE
UIPickerView with complex data

### ISSUE THREAD

**Issue by apauly** [nicklockwood/FXForms#343]
I'm trying to create 2 dependent fields that are both filled with remote content. Let's call them ```manufacturer``` and ```model```. The remote API provides ids and names for each record. The question is, how can I add a UIPickerView that shows the names to the user, but selects the related ID? The behavior I'm looking for is similar to a HTML select input. Is this currently possible with FXForms?

**Comment by nicklockwood** [comment]
If you set the options value of the field yo be an array of the ids, you can use a valueTransformer to display these as human-readable names.

The country select menu in the example app demonstrates how to do this (it maps country names to codes).

**Comment by apauly** [comment]
Ok, cool. I just wasn't sure if there's build in support for storing and handling those custom key-value pairs. But then I'll just do it by myself ;)
