### ISSUE TITLE
? : How to get slider value when subclassing from FXBaseCell isn't possible

### ISSUE THREAD

**Issue by wm-j-ray** [nicklockwood/FXForms#362]
Nick,

I'm having a tough time getting form values in general.  The process isn't clear to me out of ignorance, but I'm specifically trying to get the value from a slider.

I have a slider control using a third party library, inheriting from UISlider directly.  I have defined a subclassed tableViewCell and nib and included FXFormField *field

    @interface SliderCell : UITableViewCell <ASValueTrackingSliderDelegate, FXFormFieldCell>
      @property (nonatomic, strong) FXFormField *field;
      @property (weak, nonatomic) IBOutlet ASValueTrackingSlider *slider;
      @property (weak, nonatomic) IBOutlet UILabel *sliderLabel;
    @end

In my form model file I have the following:

    -(NSDictionary *)  tensionLevelField {
        return @{FXFormFieldCell: [SliderCell class]};
     }

I am using a custom viewController with the following pertinent properties:

     @interface FormViewController : UIViewController <FXFormControllerDelegate>
      @property (weak, nonatomic) IBOutlet UITableView *tableView;
      @property (nonatomic, strong) FXFormController *formController;
     @end

The form displays and allows entry with no issues, my custom cell (the SliderCell) displays and 'works' correctly, but I do not get the value of the slider when I dump the form's properties.

I guess, in general, I can't really figure out the best practices for getting form values in their entirety as well as getting a particular field's value programatically.  And I don't understand why the value for the slider isn't being captured by the form/formController.  

Thank you so much for any help.  This is another great library from you and I continue to learn from your code.

**Comment by nicklockwood** [comment]
The slider needs to set the value of it's cell.field when it changes, so if you haven't already done so, you should add this inside your custom cell:

    [self.slider addTarget:self action:@selector(didChange:)];

    ...

    - (void)didChange {
        self.field.value = @(self.slider.value);
    }

To get the forms values as a dictionary, you can use KVC and say something like:

    NSDictionary *values = [myForm dictionaryWithValuesForKeys:@[@"field1", @"field2", etc...]];

Or, if you follow the dynamic form example, you can create a form that stores all its values in a dictionary anyway, which you can access directly.

**Comment by wm-j-ray** [comment]
OK, I'm back...Sorry
When the slider goes off the screen either do to a navController push or pop, or scrolling out of view, the slider value is not maintained.  I did add a property to the slider cell, like so...

     @property(nonatomic) float value;

What am I missing?

**Comment by nicklockwood** [comment]
Yes, it's due to reuse. Just as you have to set the cell.field.value when you update the slider, you also have to set the cell.slider value when the field changes.

Override setField: on the cell, like this:

    - (void)

**Comment by wm-j-ray** [comment]
Since I'm not subclassing from from FXFormBaseCell or the existing FXFormCell class for the slider, where would this code go and how does it get called?

I tried to actually subclass from FXFormSliderCell previously with no success so I did a one-off implementation as described in my opening comment.

**Comment by nicklockwood** [comment]
You should be able to subclass FXFormBaseCell and save yourself some hassle, but if you're just using UITableViewCell as the base, change it to:

    @synthesize field = _field; // field is part of FXFormFieldCell protocol. This creates ivar and accessors

    - (void)setField:(FXFormField)field
    {
        _field = field;
        self.slider.value = field,value.floatValue;
    }

**Comment by wm-j-ray** [comment]
Finally, 
Got it working with this:

     - (void) didChange {
         self.field.value = @(self.slider.value);
     } 

     - (void) setField:(FXFormField *)field
     {
       _field = field;
        self.slider.value = [field.value floatValue];
     }


Thanks again so much for the help.
