### ISSUE TITLE
Resetting Form

### ISSUE THREAD

**Issue by j-dawg** [nicklockwood/FXForms#368]
How do you reset the form?

**Comment by nicklockwood** [comment]
Init a new form object and assign it to the form property, then call reloadData on the tableView.

**Comment by j-dawg** [comment]
In Swift `self.tableView.reloadData()` doesn't seem to reset the form.

**Comment by nicklockwood** [comment]
No, that just reloads the same form object. To reset the form you need to also update the form object first, like this:

    self.form = MyForm()
    self.tableView.reloadData()

**Comment by j-dawg** [comment]
Ah cool. I misunderstood.

Excellent, got it working.

**Comment by nicklockwood** [comment]
👍🏽
