### ISSUE TITLE
Demo App Crashes with recent changes

### ISSUE THREAD

**Issue by barrettj** [nicklockwood/FXForms#374]
Recent changes (last month or so) have caused the demo app to crash.

Reproduction Steps:
Run "BasicExample" on an iPad
Tap "Registration"
Tap "Country"

App will Crash 100% of the time.

**Comment by barrettj** [comment]
I should add that I'm also experiencing this is my shipping apps, and have reverted to that last cocoapods release to fix it.

**Comment by lm2s** [comment]
This seems to be the same issue as #373 (https://github.com/nicklockwood/FXForms/issues/373)

**Comment by barrettj** [comment]
1.2.13 appears to have fixed this
