### ISSUE TITLE
What is the state of FXForm project? Is it still alive?

### ISSUE THREAD

**Issue by abbasmousavi** [nicklockwood/FXForms#382]
@nicklockwood 

I have used FXForms in some of my projects, thanks for this awesome work. I want to know what is the state of development of this project and the future of it. It has nearly 150 issues and 30 pull requests, mostly without any answer from you. Will you continue development and maintenance of FXForms in future? Can we, users of FXForm, help you in any form?

**Comment by nicklockwood** [comment]
I will continue to support it, but I can't commit to any specific features or timelines.

I've just submitted version 1.2.13 which works on Xcode 7.0 / iOS 9.

Most issues seem minor. I'll review them as and when I can.
