### ISSUE TITLE
UIColor from JSON

### ISSUE THREAD

**Issue by hjanuschka** [nicklockwood/FXForms#400]
hello

using FXForms, in almost all projects i am involved.
but one question still open, how to specify a color value in a JSON Dictionary loaded via REST call.

(e.g.: in the Dynamicfields sample)

regards

**Comment by nicklockwood** [comment]
You could use a hex string and convert it using my ColorUtils library.

**Comment by hjanuschka** [comment]
- (NSArray *)fields {
    }

i am doing it in a similiar way, looping threw the json finding values with `#` and replacing value with a a uicolor, just thought, there is a built in way in FXForms, issue can be closed
