### ISSUE TITLE
How to set default value for BOOL?

### ISSUE THREAD

**Issue by realcarlos** [nicklockwood/FXForms#417]
I set it like this:
@{FXFormFieldKey: @"rememberMe",
               FXFormFieldDefaultValue:@YES ,
               FXFormFieldHeader: @""},

But it still display   off.

**Comment by nicklockwood** [comment]
Default values don't work that way. Default values are the value used when a field is reset to null. BOOL values can't be null, so they can't be reset.

To set the value to YES by default, just set self.rememberMe = YES in the init method of your form object.
