### ISSUE TITLE
Got an error on FXForms (1.2.14)

### ISSUE THREAD

**Issue by arkilis** [nicklockwood/FXForms#426]
Property 'cellLayoutMarginsFollowReadableWidth' not found on object of type 'UITableView *'

FXForms.m Line 2523.

I have used the FxForm on the other projects, the old version does not have the problem. Does anyone know any solution? Thanks!

**Comment by frakman1** [comment]
See this issue:
https://github.com/nicklockwood/FXForms/issues/433
